name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      ANDROID_NDK_HOME: /home/runner/.buildozer/android/platform/android-ndk-r25b
      ANDROID_NDK_ROOT: /home/runner/.buildozer/android/platform/android-ndk-r25b
      P4A_PYTHON_VERSION: 3.11.9

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5 libncurses-dev libtinfo5 cmake libffi-dev libssl-dev

      - name: Install NDK 25b
        run: |
          mkdir -p $HOME/.buildozer/android/platform
          cd $HOME/.buildozer/android/platform
          wget -q https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
          unzip -q android-ndk-r25b-linux.zip
          rm android-ndk-r25b-linux.zip

      - name: Install Buildozer
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install buildozer==1.5.0 cython==0.29.36

      - name: Clean old build cache
        run: rm -rf.buildozer

      - name: Build APK
        run: yes | buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Calc-APK
          path: bin/*.apk
